name: Build and Test

run-name: Build and run tests in ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: mlugg/setup-zig@v2.2.1
        with:
          version: 0.17.0-dev.2125+0d600e488
      - run: |
          zig build all --summary all
